### PR TITLE
The gettrackinfo caused a deadlock on vuduo2.

### PR DESCRIPTION
**Pull request by christophecvr**
The commented loop in this commit caused sometimes a deadlock on vuduo2.
 Box remained with sandkeeper only power reset avbl.
 This bug shows up when playing dvd  iso files.
 But also some iptv(or just free streams) caused the vuduo2 to freeze with sandkeeper.
 With the LCD4Linux removed this never happened.
 Suspect same problem there.
 With this second loop gettrackinfo commented no problems any more.

```
modified:   usr/lib/enigma2/python/Plugins/Extensions/LCD4linux/plugin.py
```

### CODE REVIEW

**Comment by eriksl** [comment]
Discuss this with the actual author please.

**Comment by christophecvr** [comment]
Well problem is that original plugin is  by dreambox ??
Anyway I added the solution. And by vuplus support i'm coming into the official vti image page.
I even suspect that this is the main cause off all problems related to vuduo2/solo2
and unexplained box lock.

Point is since I corrected this plugin I've never had any unexplained problem boxfreeze by vuduo2 anymore.

**Comment by eriksl** [comment]
The version we issue has nothing to do with the original VU+ version.

Go to http://www.i-have-a-dreambox.com/wbb2/thread.php?threadid=165337

**Comment by christophecvr** [comment]
In the mean time the reason is found and aknowledged by one off the developpers self.
http://forums.openpli.org/topic/38616-playing-off-dvdiso-and-resume/page-2

**Pull request closed without merging**
